name: Sample Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build-and-comment:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

 #     - name: Run tests
 #       run: npm test

      - name: Generate JWT
        id: jwt
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private-key.pem
          set PRIVATE_KEY_PATH=private-key.pem
          npx github-app-jwt "%PRIVATE_KEY_PATH%" %APP_ID%

      - name: Get Installation access token
        id: get-token
        run: |
          curl -XPOST -H "Authorization: Bearer ${{ steps.jwt.outputs.token }}" \
            -H "Accept: application/vnd.github.machine-man-preview+json" \
            "https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens" | jq -r .token > token.txt

      - name: Run action
        run: |
          export TOKEN=$(cat token.txt)
          export GITHUB_TOKEN=$TOKEN
          npm run action
