name: Auto merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }} # Dependabotのプルリクエストのみ
    runs-on: ubuntu-latest
    permissions:                                 # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub CLIのクレデンシャル
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge # GitHub CLIでマージ
