name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source                                     # ステップIDを設定
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUTへ書き出し
      - env:
          RESULT: ${{ steps.source.outputs.result }}   # stepsコンテキストから参照
        run: echo "${RESULT}"
